In [1]:
import sys,os

In [2]:
sys.path.append(os.pardir)

In [3]:
import numpy as np

In [4]:
from common.functions import softmax,cross_entropy_error
from common.gradient import numerical_gradient

In [5]:
#以一个简单的神经网络为例 验证神经网络W矩阵的梯度的求解
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) # 使用高斯分布进行初始化一个大小为2X3的神经网络矩阵W
    
    def predict(self,x):#使用神经网络前一层的输出以及矩阵W进行下一层输入的预测
        return np.dot(x,self.W)
    
    def loss(self,x,t):#计算交叉熵误差
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y,t)
        
        return loss#返回计算好的交叉熵误差

#### 尝试使用simpleNet这个简单的神经网络模型

In [6]:
net = simpleNet()
print(net.W)#输出神经网络的权重W

[[-0.54394813 -0.77223677 -0.76097451]
 [ 0.07758443 -0.82793071  0.96856005]]


In [7]:
x = np.array([0.6,0.9]) #自定义输入

In [8]:
p = net.predict(x) # 根据自定义输入确定输出结果

In [9]:
print(p)

[-0.2565429  -1.2084797   0.41511934]


In [10]:
np.argmax(p) #输出预测结果标签

2

In [11]:
t = np.array(3*[0])
t[np.argmax(p)] = 1 #设置正确解标签的位置
t

array([0, 0, 1])

In [12]:
net.loss(x,t) #计算损失函数对应在x t下的值

0.535350110455962

In [13]:
def f(W):#定义损失函数的表达式
    return net.loss(x,t)
dW = numerical_gradient(f,net.W)#求解损失函数的值
dW

array([[ 0.17945365,  0.0692678 , -0.24872145],
       [ 0.26918048,  0.1039017 , -0.37308218]])

#### 使用lambda表达式来实现梯度的计算

In [14]:
f = lambda w:net.loss(x,t)
dW = numerical_gradient(f,net.W)

In [15]:
dW

array([[ 0.17945365,  0.0692678 , -0.24872145],
       [ 0.26918048,  0.1039017 , -0.37308218]])