In [1]:
import numpy as np

#### 生成numpy数组

In [2]:
x = np.array([1.0,2.0,3.0]) # np.array接收Python列表作为参数，生成Numpy数组numpy.ndarray
print(x)

[1. 2. 3.]


In [3]:
type(x) # 查看数组X的类型

numpy.ndarray

#### numpy的算术运算

In [4]:
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])
print(x + y) # 对应元素的加法

[3. 6. 9.]


In [5]:
print(x - y) # 对应元素的减法

[-1. -2. -3.]


In [6]:
print(x * y) # elementwise product

[ 2.  8. 18.]


In [7]:
print(x / y) #对应元素的除法

[0.5 0.5 0.5]


#### numpy的广播

In [8]:
x = np.array([1,2,3])#每一个元素除以2.0构成新的ndarray
x / 2.0

array([0.5, 1. , 1.5])

#### Numpy的N维数组

In [9]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [10]:
A.shape # 矩阵A的形状

(2, 2)

In [11]:
A.dtype # 矩阵元素的数据类型

dtype('int32')

In [12]:
B = np.array([[3,0],[0,6]]) # 矩阵的加法
A + B

array([[ 4,  2],
       [ 3, 10]])

In [13]:
A * B # A左乘B

array([[ 3,  0],
       [ 0, 24]])

#### Numpy张量的广播

In [14]:
A*10

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20]) # 1X2的二维数组
A * B

array([[10, 40],
       [30, 80]])

#### 访问元素

In [16]:
X = np.array([[51,55],[14,19],[0,4]]) # 定义二维张量
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [17]:
X[0] # 第0行

array([51, 55])

In [18]:
X[0][1] # (0,1)元素

55

In [19]:
# 使用for访问各个元素
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


#### 使用数组访问各个元素

In [20]:
X = X.flatten() # 将X按照行主序转换成一维数组
print(X)

[51 55 14 19  0  4]


In [21]:
X[np.array([0,2,4])] # 获取索引为0 2 4的元素

array([51, 14,  0])

In [22]:
#从数组中抽取满足一定条件的元素 >15
X>15

array([ True,  True, False,  True, False, False])

In [23]:
X[X>15] #满足条件的元素会被提取

array([51, 55, 19])