In [1]:
import numpy as np

###### 第一层的数据准备

In [2]:
X = np.array([1.0,5.0])
W1 = np.array([
    [0.1,0.3,0.5],
    [0.2,0.4,0.6]
])
B1 = np.array([
    0.1,0.2,0.3
])

print(W1.shape) # (2,3)
print(B1.shape) # (3,)
print(X.shape) # (2,)

(2, 3)
(3,)
(2,)


###### 处理从第一层到第二层之间的神经网络信号的传递

In [3]:
A1 = np.dot(X,W1)+B1
A1

array([1.2, 2.5, 3.8])

#### 经过sigmoid函数处理后的神经网络信号传递

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
W2 = np.array([ #Wk 的规模取决于相邻层神经网络节点的规模
    [0.1,0.4],  #前一层的节点数量是行数后一层节点数量为列数
    [0.2,0.5],  #这里面的数量的计算不包含偏置b
    [0.3,0.6]
])
Z1 = sigmoid(A1) #第一层的输出变成了第二层的输入
B2 = np.array([0.1,0.2])

print(Z1.shape) #(3,)
print(W2.shape) #(3,2)
print(B2.shape) #(2,)

(3,)
(3, 2)
(2,)


In [6]:
A2 = np.dot(Z1,W2) + B2
A2

array([0.65511646, 1.55635206])

##### 第二层的输入数据

In [7]:
Z2 = sigmoid(A2)
Z2

array([0.65816252, 0.82582927])

In [8]:
def identify_function(x):#为了保持和此前风格的一致性，定义一个输出层的激活函数
    return x

In [9]:
W3 = np.array([
    [0.1,0.3],
    [0.2,0.4]
])
B3 = np.array([
    0.1,0.2
])

A3 = np.dot(Z2,W3) + B3

In [10]:
Y = identify_function(A3)
Y

array([0.33098211, 0.72778046])